.PHONY all:
all:
	gcc -Wall -D PART1 assignment3.c -o diskinfo
	gcc -Wall -D PART2 assignment3.c -o disklist
	gcc -Wall -D PART3 assignment3.c -o diskget
	gcc -Wall -D PART4 assignment3.c -o diskput

.PHONY clean:
clean:
	-rm diskinfo disklist diskget diskput
